config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'

  get 'todos/:id/edit', to: 'todos#edit', as: 'edit'
  patch 'todos/:id', to: 'todos#update', as: 'todo'
  delete 'todos/:id', to: 'todos#destroy'

  get 'todos/list', to: 'todos#list'
  get 'todos/:id', to: 'todos#show'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete'

  root 'todos#index'
  # resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :find_todo, only: [:show, :edit, :update, :destroy, :complete]
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save!
    redirect_to todos_path
  end

  def show
  end

  def edit
  end

  def update
    # fail
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo.destroy
    redirect_to todos_path
  end

  def complete
    @todo.update(:completed => true)
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
    @pendientes = @todos.select  { |item| item[:completed] == false }
    @completos = @todos.select { |item| item[:completed] == true }
  end

  def find_todo
    @todo = Todo.find(params[:id])
  end
  private

  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg">
  <a class="navbar-brand" href="#">ToDo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
          <%= link_to 'Index', todos_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to 'List', todos_list_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to 'Nuevo', todos_new_path, class: 'nav-link' %>
      </li>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>


  </body>
</html>

app/views/todos/_formulario.html.erb
<%= form_with model: @todo, local: true do |f| %>
  <!-- <input type="hidden" value="<%=form_authenticity_token%>"name="authenticity_token"> -->

  <div class="form-group">
    <%= f.label :description, "Descripcion" %>
    <%= f.text_field :description , class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :completed, "Completo"%>
    <%= f.check_box :completed %>
  </div>

  <div class="float-right">
    <%= f.submit "Guardar", class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<div class="container">
  <h1>Editar</h1>
  <div class="">
    <%= render 'todos/formulario' %>
  </div>

</div>

app/views/todos/index.html.erb
<div class="container">
  <div class="contiene-add-new-btn">
    <%= link_to 'Agregar nuevo Todo', todos_new_path, class: 'btn btn-primary btn-sm' %>
  </div>


  <% @todos.each do |todo| %>
    <div class="card">
      <div class="card-header">
        <div class="form-group">
          <% if !todo.completed %>
            <%= link_to 'Completar', complete_path(todo), class: 'btn btn-success btn-sm', :disabled => false %>
          <% else %>
            <%= link_to 'Listo', complete_path(todo), class: 'btn btn-success btn-sm disabled', :disabled => true %>
          <% end %>
        </div>
        <%= todo.description %>
      </div>
      <div class="card-body">
        <%= link_to 'Show', todo, class: 'btn btn-info btn-sm' %>
        <%= link_to 'Editar', edit_path(todo), class: 'btn btn-warning btn-sm' %>
        <%= link_to "Eliminar", todo, method: :delete, class: 'btn btn-danger btn-sm' %>
      </div>
    </div>

  <% end %>

</div>

app/views/todos/list.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 list-group">
      <h2>Pendientes</h2>
      <% @pendientes.each do |todo| %>
        <div class="list-group-item border-warning">
          <p> <%= todo.description %> </p>
        </div>
      <% end %>

    </div>
    <div class="col-6 list-group">
      <h2>Completados</h2>
      <% @completos.each do |todo| %>

        <div class="list-group-item border-success">
          <p> <%= todo.description %> </p>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/todos/new.html.erb
<div class="container">
  <h1>Nuevo ToDo</h1>
  <div class="">
    <%= render 'todos/formulario' %>

  </div>
</div>

app/views/todos/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h2> <%= @todo.description %> </h2>
    <% if  @todo.completed %>
      <p>Completo: Si</p>
    <% else %>
      <p>Completo: No</p>
    <% end%>
    <div class="float-right">
      <%= link_to 'Volver', todos_path, class: 'btn btn-outline-primary' %>
    </div>

  </div>
</div>